{{- if .Values.database.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskora.fullname" . }}-database
  labels:
    {{- include "taskora.database.labels" . | nindent 4 }}
spec:
  type: {{ .Values.database.service.type }}
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "taskora.database.selectorLabels" . | nindent 4 }}
{{- end }}
