{{- if .Values.redis }}
{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskora.fullname" . }}-redis
  labels:
    {{- include "taskora.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: {{ .Values.redis.service.type | default "ClusterIP" }}
  ports:
    - name: redis
      port: {{ .Values.redis.service.port | default 6379 }}
      targetPort: 6379
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "taskora.name" . }}-redis
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
{{- end }}
