{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taskora.fullname" . }}-secrets
  labels:
    {{- include "taskora.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.databaseUrl }}
  DATABASE_URL: {{ .Values.secrets.databaseUrl | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.cohereApiKey }}
  COHERE_API_KEY: {{ .Values.secrets.cohereApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.betterAuthSecret }}
  BETTER_AUTH_SECRET: {{ .Values.secrets.betterAuthSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.geminiApiKey }}
  GEMINI_API_KEY: {{ .Values.secrets.geminiApiKey | b64enc | quote }}
  {{- end }}
{{- end }}
